# Description
# ===========
# This workflow is triggered each time a milestone is closed
# It builds the jar, generates release notes, pushes a new tag
# and makes a draft release with these elements.
---
name: Tag & Release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Est-ce que la release doit être en brouillon?'
        default: true
        required: false
        type: boolean
      prerelease:
        description: "Est-ce que c'est une pre-release?"
        default: true
        required: false
        type: boolean
      tag:
        description: "Optionnel : Spécifier un tag ou prend la version du pom.xml?"
        required: false
        type: number

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Build with Maven
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set tag and project values
      run: |
        if [[ -n "${{ inputs.tag }}" ]]; then
          echo "${{ inputs.tag }}" >> $GITHUB_ENV
        else
          echo "tag=$(cat pom.xml | grep "<icode\.version>.*</icode\.version>" | head -1 |awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
        fi
        echo "project=$(echo ${{ github.repository }} | awk -F '/' '{print $2}')" >> $GITHUB_ENV
    - name: Create a tag for the release
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email catlab@cnes.fr
        git tag -a ${{ env.tag }} -m "Release ${{ env.tag }}"
        git push origin ${{ env.tag }}
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        artifacts: "icode-app/target/icode-*.zip,icode-ide/fr.cnes.icode.repository/target/products/icode-ide.product-*.zip,icode-ide/fr.cnes.icode.repository/target/fr.cnes.icode.repository-*.zip"
        tag: ${{ env.tag }}
        name: ${{ env.project }} ${{ env.tag }}
        draft: ${{inputs.draft}}
        generateReleaseNotes: true
        prerelease: ${{inputs.prerelease}}
        token: ${{ secrets.GITHUB_TOKEN }}
